### ISSUE TITLE
A for line 2 on aidon

### ISSUE THREAD

**Issue by tux-** [robinsmidsrod/ams-han-decoder#7]
I can not seem to see A for L2 in the json, only for L1 and L3. Is this a bug or a feature? ;)

**Comment by robinsmidsrod** [comment]
It's a bug in the data from the meter. The data is just not there (at least on mine). If you run the command on the terminal with output of the decoded payload (not what it sends to MQTT, which is the payload mapped to the schema, e.g. KFM_001) you'll notice that the OBIS entry for L2 current in ampere is not the same as the others. Nothing I can do about that, unfortunately. Trying to calculate it based on the other values is error-prone and something I'd not try to do in the application, as it complicates the architecture for something I consider a firmware bug in meters. If you use Home Assistant, I'd try my luck on a creating a template sensor based on the calculation I've seen floating around. Not sure where I saw it, but I think some home automation forums that talk about the AMS HAN spec (in Norway) have some details.
